### ISSUE TITLE
version bump needed (to 0.4)

### ISSUE THREAD

**Issue by clach04** [ActianCorp/ingres_sa_dialect#21]
The current headrevs work with SA v2 and v1.x., this warrents a version bump (0.3 did not with with 2).

Cross ref https://github.com/ActianCorp/ingres_sa_dialect/issues/10

**Comment by clach04** [comment]
@hab6 close this with recent PR?

**Comment by hab6** [comment]
Closing per #23 which bumped version to 0.4.
